spring:
    datasource:
        url: jdbc:mysql://avnadmin:AVNS_mkpOJ3wmfd_3krz_NPT@mysql-2434ec8b-give-hub.l.aivencloud.com:16565/YoloFarm?sslMode=REQUIRED
        username: avnadmin
        password: AVNS_mkpOJ3wmfd_3krz_NPT
        driver-class-name: com.mysql.cj.jdbc.Driver 
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
  servlet:
    context-path: /api

adafruit:
    username: khanguyentrong2k4
    adaaccess: aio_XLvf64TcbABZKgM4BfcApo0zU2mW
    broker: tcp://io.adafruit.com:1883
