spring:
    datasource:
        url: jdbc:mysql://avnadmin:AVNS_mkpOJ3wmfd_3krz_NPT@mysql-2434ec8b-give-hub.l.aivencloud.com:16565/YoloFarm?sslMode=REQUIRED
        username: avnadmin
        password: AVNS_mkpOJ3wmfd_3krz_NPT
        driver-class-name: com.mysql.cj.jdbc.Driver 
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    websocket:
        enabled: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
server:
  port: 8080
  servlet:
    context-path: /api

adafruit:
    username: quangtu2811
    adaaccess: aio_UpEI44JhIWs9cMvraOjnlOeBmV1L
    broker: tcp://io.adafruit.com:1883
